server:
  host: localhost
  port: 8080

log:
  level: info

meta_store:
  host: "localhost"
  port: 5432
  user: "minerva"
  password: "m1n3rv@"
  dbname: "git-server-poc"
  sslmode: "disable"

object_store:
  endpoint: http://localhost:8000
  access_key: CRJFQ1D9O5CN78V4F4FR
  secret_key: AnyhjoBjqw3QkbQqXzwb6SrAPpoefIWLYyC7raSY
  bucket: git-objects
  region: us-east-1
