version: '3.8'
name: git-server-poc-devenv

services:
  microceph:
    build:
      context: ./microceph
    image: custom/microceph:latest
    container_name: microceph
    privileged: true
    volumes:
      - snapd_data:/var/lib/snapd
      - /dev:/dev
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cgroup: host
    tmpfs:
      - /run
      - /run/lock
    ports:
      - "8000:80"

  postgres:
    image: postgres:18.1-trixie
    container_name: postgres
    environment:
      POSTGRES_USER: minerva
      POSTGRES_PASSWORD: m1n3rv@
      POSTGRES_DB: git-server-poc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
  snapd_data:
